### ISSUE TITLE
Apply Corncob into multi-datasets

### ISSUE THREAD

**Issue by Zhujun-zhujun** [statdivlab/corncob#136]
Hi, 
Now, I collected 9 datasets about 16S amplicons from human gut microbiota, and the datasets were be merged. I need to test the taxon  difference between two groups (Ulcerative Colitis cohorts vs Healthy Cohort). Considering the big difference among different datasets, It's important to exclude the impact from different datasets. Therefore, how to estimate the effect of studyID ( a vriable that is a label for different datasets) or eliminate it that is indispensable. 
I appreciate it.

**Comment by adw96** [comment]
Hi @Zhujun-zhujun -- I apologize for the delay on this. In case an answer is still helpful, if you are committed to using corncob, then I would encourage you to adjust for study. i.e., your code might look like `formula = ~ study + disease`

One of the limitations of corncob is that is not robust to differential detection. A newer method that we've developed, [radEmu](https://github.com/statdivlab/radEmu/), directly addresses this. We are now recommending that people use `radEmu` for differential abundance instead of `corncob`. You would adjust for study your radEmu model to account for the different datasets. 

Best wishes with your analysis and I apologize that we were so late to get a response to you.
