### ISSUE TITLE
volcano plot 

### ISSUE THREAD

**Issue by Diane-R** [statdivlab/corncob#154]
Hello, 

I am attempting to generate a volcano plot using corncob estimated coefficients. I am using the values from the mu.damGenoKO.Estimate for the Y-axis, and the p_FDR for the X axis. Would this estimated coefficient be considered a fold change? Are these values log transformed? Is this even an appropriate way of viewing corncob data? 

Also, we lost many of our taxa because they had NA p_fdr values. These are likely because those taxa are only present in one group. I attempted to get them back by adding a pseudocount of +1 to each value and it seemed to work to get a point for each taxon. Would this be an appropriate way to transform the data to get each taxon represented? 

Thank you in advance!

**Comment by adw96** [comment]
Hi @Diane-R! 

- Coefficients associated with the mean (mu coefficients) should be interpreted on the logit-scale, not the fold-difference scale. Similar to logistic regression, these parameters estimate the difference in the logit-transformed probability of observing a read from the taxon in (eg) group 1 compared to group 2 (and, eg, the groups could be defined by either continuous or discrete covariates). You can take a look at the paper for the exact form of the model -- the relevant line is logit(mu_i) = beta0+beta1 * X_i^T. 
- Volcano plots are a fine way of viewing corncob data. They are not my thing, but genomics folks seem to like them and are accustomed to interpreting them. 
- I recommend against adding pseudocounts to force corncob to give you parameter estimates and testing results. Altering your data to make a model fit is always a bad idea (in my opinion). Fortunately, it's pretty easy to interpret the perfect separation taxa! These are taxa that were observed in one group but not the other. I would take a close look at these taxa, because they can be very interesting scientifically -- they perfectly discriminate between groups! There are two options: (A) extremely interesting because the abundance of the taxon was high in one group and absent in the other -- I think this is the most exciting case!!!, or (B) the taxon was "sparse" = abundance of the taxon was low in almost every sample, but present in one of the groups, which is less interesting as it signals rarity rather than scientific meaning. In short, I encourage you to take a close look at these taxa to determine if you are in (A) 🥳  or (B) 🤷 

Hope that helps!
