### ISSUE TITLE
Using differentialTest including subsampling

### ISSUE THREAD

**Issue by imuscettola** [statdivlab/corncob#182]
I would like to run a differential abundance test on my microbial dataset collected from soils effected by wildfire. In my experimental design I collected 3 soil samples per plot and in my initial analyses of community composition I have found that those samples are not independent. I would like to run a differentialTest on my dataset that incorporates the subsampling of the experimental design. Similar to in a linear mixed model that I would incorporate the replicate at each plot as a random effect. Thanks in advance for your help.

**Comment by adw96** [comment]
Thanks for you great question, @imuscettola . Random effects are not implemented in corncob. As corncob is in "essential maintenance only" phase, we are not planning to implement this feature. I'm very sorry.

That said, the reason why we are triaging development to corncob is because we have a new package for microbiome differential abundance that we believe is uniformly better than corncob (which was already very good) 😸  You can check it out at [https://github.com/statdivlab/radEmu](https://github.com/statdivlab/radEmu)

There's more good news -- the cluster correlated sampling design you describe can be dealt with in `radEmu` using the argument `cluster`. [Here](https://statdivlab.github.io/radEmu/articles/radEmu_clustered_data.html) is a beautiful vignette showing you how to do it. 

We are actively maintaining and helping new users of radEmu, so please don't hesitate to let us know if you need support there. 

I'm sorry that we are not able to help you with corncob, but we hope that you like radEmu.
